services:

  linkaudit-service:
    build:
      context: .
      dockerfile: linkaudit/service/Dockerfile
    ports:
      - "9091:9091"

  shortener-service:
    build:
      context: .
      dockerfile: shortener/service/Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "9090:9090"
    depends_on:
      - linkaudit-service
